version: '3'

services:
  homeservices:
    container_name: homeservices
    environment:
      - DOCKER_INSTANCE=TRUE
    image: thornpar/homeservices:latest
    ports: 
      - "8001:80"
    depends_on:
      - db
  db: 
    image: microsoft/mssql-server-linux
    container_name: db
    volumes:
      - db-data-homeservices:/var/opt/mssql/
    ports:
        - "1433:1433"
    environment:
      SA_PASSWORD: password123(!)
      ACCEPT_EULA: "Y"

volumes:
  db-data-homeservices: